name: Update Changelog

on:
  workflow_dispatch:
    inputs:
      title:
        description: "release title"
        required: false
        default: "WebRTC SDK Vx.x.x"
      description:
        description: "release description"
        required: false
        default: "description"
      ref:
        description: "Git ref (branch) to update"
        required: false
        default: "main"
jobs:
  publish:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    env:
      TARGET_BRANCH: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.event.release.target_commitish || 'main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ env.TARGET_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release description
        working-directory: packages/js
        run: |
          body_escaped=$(printf '%s\n' "${{ github.event.release.body }}" | sed 's/$/\\/')

          sed -i '' '1i\
          ## [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }}) (${{ github.event.release.created_at }})\
          \\
          $body_escaped
          ' CHANGELOG.md

      - name: Commit and push changes
        working-directory: packages/js
        run: |
          git config user.name TelnyxIntegrations
          git config user.email integrations@telnyx.com
          git add CHANGELOG.md
          git commit --no-verify -m "Update CHANGELOG.md with release ${{ github.event.release.tag_name || github.event.inputs.title }}"
          git push -u origin ${{ env.TARGET_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
